### ISSUE TITLE
requirements for neurolibre

### ISSUE THREAD

**Issue by ltetrel** [neurostuff/ohbm2021-nimare-tutorial#1]
In the case of a Neurolibre submission, it is better to remove `jupyter` dependencies because the base image (in the user environment) already have it.
Can you remove them ? https://github.com/neurostuff/ohbm2021-nimare-tutorial/blob/c7091f5da0d31f8807d6f1006f3c4014a6fd8a7d/binder/requirements.txt#L3-L4

**Comment by tsalo** [comment]
Just jupyter and jupytext, right? Can do.

**Comment by tsalo** [comment]
Done in 67518d4.

**Comment by ltetrel** [comment]
So actually I am not sure `jupytext` is included in `jupyter` so if you need it you may want to actually keep it.

**Comment by tsalo** [comment]
I'm pretty sure it's unnecessary for the actual tutorial, so I'll keep it out. Thanks.
