### ISSUE TITLE
Neurolibre submission: data path

### ISSUE THREAD

**Issue by ltetrel** [neurostuff/ohbm2021-nimare-tutorial#2]
Hi Taylor,
Make sure yours paths points to the right place in the notebook:
`DATA_DIR = op.abspath("../data/nimare_tutorial/")`
=> `DATA_DIR = op.abspath("../data/nimare_tutorial/osfstorage/")`
(you should mimic the fact that you pull from osf)

**Comment by tsalo** [comment]
Thanks! Done in ce37178.
