### ISSUE TITLE
Add script or optional command to download data to first cell of tutorial

### ISSUE THREAD

**Issue by tsalo** [neurostuff/ohbm2021-nimare-tutorial#4]
@koudyk you mentioned you were willing to do this in today's call. Is that alright?

**Comment by ltetrel** [comment]
What you could do @koudyk is to have a little bash script in the root of the repo that runs `repo2data`, and run that script in the first cell.
That way (if Neurolibre), it will by-pass the download (it was already downloaded when building the environment), if not (mybinder/collab/locally) repo2data will fetch the data and put it in your root repo `./data/nimare_tutorial`. But rememeber to add it in the requirement file.

Or you can also create this fetch script using OSF python-api. And check manually if the data folder exists in the notebook.
